<testsuites>
  <testsuite name=":myProject:throwExceptionNoMessage" tests="1">
    <testcase name="[:myProject:throwExceptionNoMessage] error: java.lang.OutOfMemoryError exception thrown" className=":myProject:throwExceptionNoMessage">
      <failure type="ERROR">An error occurred, java.lang.OutOfMemoryError exception thrown

* Causal chain is:
	org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':myProject:throwExceptionNoMessage'.
	java.lang.OutOfMemoryError

* Full exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':myProject:throwExceptionNoMessage'.
Caused by: java.lang.OutOfMemoryError

</failure>
    </testcase>
  </testsuite>
  <testsuite name="./gradlew runFix" tests="1">
    <testcase name="[:throwExceptionWithSuggestedFix] error: ExceptionWithSuggestedFixMessage" className="./gradlew runFix">
      <failure type="ERROR">ExceptionWithSuggestedFixMessage

* Causal chain is:
	org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':throwExceptionWithSuggestedFix'.
	com.palantir.gradle.failurereports.exceptions.ExceptionWithSuggestion: ExceptionWithSuggestedFixMessage

* Full exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':throwExceptionWithSuggestedFix'.
Caused by: com.palantir.gradle.failurereports.exceptions.ExceptionWithSuggestion: ExceptionWithSuggestedFixMessage

</failure>
    </testcase>
  </testsuite>
  <testsuite name=":myProject:throwGradleException" tests="1">
    <testcase name="[:myProject:throwGradleException] error: This is a normal gradle exception" className=":myProject:throwGradleException">
      <failure type="ERROR">This is a normal gradle exception

* Causal chain is:
	org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':myProject:throwGradleException'.
	org.gradle.api.GradleException: This is a normal gradle exception

* Full exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':myProject:throwGradleException'.
Caused by: org.gradle.api.GradleException: This is a normal gradle exception

</failure>
    </testcase>
  </testsuite>
  <testsuite name="./gradlew fixMe" tests="1">
    <testcase name="[:myProject:throwInnerExceptionWithSuggestedFix] error: InnerExceptionWithSuggestedFixMessage" className="./gradlew fixMe">
      <failure type="ERROR">InnerExceptionWithSuggestedFixMessage

* Causal chain is:
	org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':myProject:throwInnerExceptionWithSuggestedFix'.
	org.gradle.api.GradleException: OuterGradleException
	com.palantir.gradle.failurereports.exceptions.ExceptionWithSuggestion: InnerExceptionWithSuggestedFixMessage
	java.lang.RuntimeException: InnerRuntimeException

* Full exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':myProject:throwInnerExceptionWithSuggestedFix'.
Caused by: org.gradle.api.GradleException: OuterGradleException
Caused by: com.palantir.gradle.failurereports.exceptions.ExceptionWithSuggestion: InnerExceptionWithSuggestedFixMessage
	... PLACEHOLDER_NUMBER more
Caused by: java.lang.RuntimeException: InnerRuntimeException
	... PLACEHOLDER_NUMBER more

</failure>
    </testcase>
  </testsuite>
</testsuites>
